global:
  server:
    endpoint: 'http://10.77.78.11:8080'          # Default: http://127.0.0.1:8080
    #    api_path: '/api/v1/otlp/v1/metrics'   # Default: "
    insecure: true                         # yes(y), true / no(n), false
  client:
    auth: 'appez'
    insecure: true
    labels:
      env: 'production'
      host_group: 'TEST'
  provider:
    interval: 1m

server:
  metrics:
    endpoint: 'http://10.77.78.11:9090'
    api_path: '/api/v1/otlp/v1/metrics'
    #    mode: 'grpc'
    insecure: true
    enabled: true
  logs:
    endpoint: 'http://10.77.78.11:3100'
    api_path: '/otlp/v1/logs'
    enabled: true
  #    mode: 'grpc'
  traces:
    endpoint: ''
    enabled: false

# clients Section
#########################
## clients에 모니터링 대상 장비들을 정의합니다.
## endpoint = 스토리지 서버의 엔드포인트(Spectrum API)
## auth = 사용할 인증 정보(auths.name)
## Insecure = TLS 설정
clients:
  - endpoint: 'https://10.77.77.140:7443'
    auth: 'prom'
    insecure: true
    labels:
      env: "production"
      host_group: "IBM"

  - endpoint: 'https://10.77.77.170:7443'
    auth: 'prom'
    insecure: true
    labels:
      env: "production"
      host_group: "IBM"
  #


auths:
  - name: 'prom'
    user: 'prometheus'
    password: 'P@ssw0rd1!'
  - name: 'admin'
    user: 'superuser'
    password: 'Passw0rd1!'

# Providers Sections
# default :
# if interval is not define, that will be to set global.
providers:
  system:
    enabled: true
  systemstats:
    enable: true
  eventlog:
    enabled: true
